spring:
  data:
    mongodb:
      uri:mongodb+srv://shubhamchoudhary0071:KDXh0dXps5dbCbuP@cluster0.kjstm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0,
      database:journals,
      auto-index-creation:true

server:
  port: 8081
  servlet:
    context-path: /journal